#!/bin/sh

echo dnsblast ${DNSHOST:=8.8.8.8} ${DNSREQUEST:=5000} ${DNSPERSEC:=10}

while true; do BLAST=`dnsblast ${DNSHOST} ${DNSREQUEST} ${DNSPERSEC} 2>&1`; echo "`date` - ${BLAST}"; sleep 2; done;
